// ios-like-picker/time/angular/src/app/wheel.component.ts
import { Component, ElementRef, ViewChild, Input } from "@angular/core"
import KeenSlider from "keen-slider"

@Component({
  selector: "wheel",
  templateUrl: "./wheel.component.html",
  styleUrls: [
    "../../node_modules/keen-slider/keen-slider.min.css",
    "./wheel.component.css",
  ],
})
export class WheelComponent {
  @Input() loop: boolean
  @Input() initIdx: number = 0
  @Input() length: number
  @Input() width: number
  @Input() perspective: string = "center"
  @Input() setValue: Function | undefined
  @ViewChild("sliderRef") sliderRef: ElementRef<HTMLElement>

  slidesPerView: number = 1
  slideDegree: number = 360 / 20
  slider: KeenSlider = null
  slideValues: string[] = []
  radius: number = 0
  wheelSize: number = 20
  setSlideValues(details) {
    const offset = this.loop ? 1 / 2 - 1 / this.slidesPerView / 2 : 0

    const values = []
    for (let i = 0; i < this.length; i++) {
      const distance =
        (details.positions[i].distance - offset) * this.slidesPerView
      const rotate =
        Math.abs(distance) > this.wheelSize / 2
          ? 180
          : distance * (360 / this.wheelSize) * -1
      const style = {
        transform: `rotateX(${rotate}deg) translateZ(${this.radius}px)`,
        WebkitTransform: `rotateX(${rotate}deg) translateZ(${this.radius}px)`,
      }
      const value = this.setValue
        ? this.setValue(i, details.absoluteSlide + Math.round(distance))
        : i
      values.push({ style, value })
    }
    this.slideValues = values
  }

  ngAfterViewInit() {
    setTimeout(() => {
      if (this.loop) this.slidesPerView = 9
      const options = {
        centered: this.loop,
        vertical: true,
        friction: 0.0025,
        initial: this.initIdx || 0,
        loop: this.loop,
        dragSpeed: (val, instance) => {
          const height = instance.details().widthOrHeight
          return (
            val *
            (height /
              ((height / 2) * Math.tan(this.slideDegree * (Math.PI / 180))) /
              this.slidesPerView)
          )
        },
        move: (s) => {
          this.setSlideValues(s.details())
        },
        rubberband: !this.loop,
        mode: "free-snap",
        slides: this.length,
        slidesPerView: this.slidesPerView,
      }

      this.slider = new KeenSlider(this.sliderRef.nativeElement, options)
      this.radius = this.slider.details().widthOrHeight / 2
      this.setSlideValues(this.slider.details())
    })
  }

  ngOnDestroy() {
    if (this.slider) this.slider.destroy()
  }
}

<div
  #sliderRef
  [ngClass]="'wheel keen-slider wheel--perspective-' + perspective"
>
  <div
    class="wheel__shadow-top"
    [ngStyle]="{
      transform: 'translateZ(' + radius + 'px)',
      '-webkit-transform': 'translateZ(' + radius + 'px)'
    }"
  ></div>
  <div class="wheel__inner">
    <div class="wheel__slides" [ngStyle]="{ width: width + 'px' }">
      <div
        *ngFor="let slide of slideValues"
        class="wheel__slide"
        [ngStyle]="slide.style"
      >
        <span>{{ slide.value }}</span>
      </div>
    </div>
    <div
      *ngIf="label"
      class="wheel__label"
      [ngStyle]="{
        transform: 'translateZ(' + radius + 'px)',
        '-webkit-transform': 'translateZ(' + radius + 'px)'
      }"
    >
      {{ label }}
    </div>
  </div>
  <div
    class="wheel__shadow-bottom"
    [ngStyle]="{
      transform: 'translateZ(' + radius + 'px)',
      '-webkit-transform': 'translateZ(' + radius + 'px)'
    }"
  ></div>
</div>

// ios-like-picker/date-time/react/src/Wheel.js
import React from "react"
import { useKeenSlider } from "keen-slider/react"
import "keen-slider/keen-slider.min.css"
import "./Wheel.css"

export default function Wheel(props) {
  const perspective = props.perspective || "center"
  const wheelSize = 20
  const slides = props.length
  const slideDegree = 360 / wheelSize
  const slidesPerView = props.loop ? 9 : 1
  const [sliderState, setSliderState] = React.useState(null)
  const [sliderRef, slider] = useKeenSlider({
    centered: props.loop,
    vertical: true,

    initial: props.initIdx || 0,
    loop: props.loop,
    dragSpeed: (val, instance) => {
      const height = instance.details().widthOrHeight
      return (
        val *
        (height /
          ((height / 2) * Math.tan(slideDegree * (Math.PI / 180))) /
          slidesPerView)
      )
    },
    move: (s) => {
      setSliderState(s.details())
    },
    rubberband: !props.loop,
    mode: "free-snap",
    slides,
    slidesPerView,
  })

  const [radius, setRadius] = React.useState(0)

  React.useEffect(() => {
    if (slider) setRadius(slider.details().widthOrHeight / 2)
  }, [slider])

  function slideValues() {
    if (!sliderState) return []
    const offset = props.loop ? 1 / 2 - 1 / slidesPerView / 2 : 0

    const values = []
    for (let i = 0; i < slides; i++) {
      const distance = sliderState
        ? (sliderState.positions[i].distance - offset) * slidesPerView
        : 0
      const rotate =
        Math.abs(distance) > wheelSize / 2
          ? 180
          : distance * (360 / wheelSize) * -1
      const style = {
        transform: `rotateX(${rotate}deg) translateZ(${radius}px)`,
        WebkitTransform: `rotateX(${rotate}deg) translateZ(${radius}px)`,
      }
      const value = props.setValue
        ? props.setValue(i, sliderState.absoluteSlide + Math.round(distance))
        : i
      values.push({ style, value })
    }
    return values
  }

  return (
    <div
      className={"wheel keen-slider wheel--perspective-" + perspective}
      ref={sliderRef}
    >
      <div
        className="wheel__shadow-top"
        style={{
          transform: `translateZ(${radius}px)`,
          WebkitTransform: `translateZ(${radius}px)`,
        }}
      />
      <div className="wheel__inner">
        <div className="wheel__slides" style={{ width: props.width + "px" }}>
          {slideValues().map(({ style, value }, idx) => (
            <div className="wheel__slide" style={style} key={idx}>
              <span>{value}</span>
            </div>
          ))}
        </div>
        {props.label && (
          <div
            className="wheel__label"
            style={{
              transform: `translateZ(${radius}px)`,
              WebkitTransform: `translateZ(${radius}px)`,
            }}
          >
            {props.label}
          </div>
        )}
      </div>
      <div
        className="wheel__shadow-bottom"
        style={{
          transform: `translateZ(${radius}px)`,
          WebkitTransform: `translateZ(${radius}px)`,
        }}
      />
    </div>
  )
}
