// basic/range/react/src/App.js
import React from "react"
import { useKeenSlider } from "keen-slider/react"
import "keen-slider/keen-slider.min.css"
import "./styles.css"

export default () => {
  const [sliderRef] = useKeenSlider({
    loop: true,
    mode: "free",
    slides: { origin: "center", perView: 2.5, spacing: 10 },
    range: {
      min: -5,
      max: 5,
    },
  })

  return (
    <div ref={sliderRef} className="keen-slider">
      <div className="keen-slider__slide number-slide1">1</div>
      <div className="keen-slider__slide number-slide2">2</div>
      <div className="keen-slider__slide number-slide3">3</div>
      <div className="keen-slider__slide number-slide4">4</div>
      <div className="keen-slider__slide number-slide5">5</div>
      <div className="keen-slider__slide number-slide6">6</div>
    </div>
  )
}

// basic/autowidth/angular/src/app/app.component.ts
import { Component, ElementRef, ViewChild } from "@angular/core"
import KeenSlider from "keen-slider"

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: [
    "../../node_modules/keen-slider/keen-slider.min.css",
    "./app.component.css",
  ],
})
export class AppComponent {
  @ViewChild("sliderRef") sliderRef: ElementRef<HTMLElement>

  slider: any = null

  ngAfterViewInit() {
    this.slider = new KeenSlider<{}>(this.sliderRef.nativeElement, {
      loop: false,
      mode: "snap",
      rtl: false,
      slides: { perView: "auto" },
    })
  }

  ngOnDestroy() {
    if (this.slider) this.slider.destroy()
  }
}

<div class="keen-slider" #sliderRef>
  <div
    class="keen-slider__slide number-slide1"
    style="min-width: 150px; max-width: 150px"
  >
    1
  </div>
  <div
    class="keen-slider__slide number-slide2"
    style="min-width: 100px; max-width: 100px"
  >
    2
  </div>
  <div
    class="keen-slider__slide number-slide3"
    style="min-width: 200px; max-width: 200px"
  >
    3
  </div>
  <div
    class="keen-slider__slide number-slide4"
    style="min-width: 500px; max-width: 500px"
  >
    4
  </div>
  <div
    class="keen-slider__slide number-slide5"
    style="min-width: 150px; max-width: 150px"
  >
    5
  </div>
  <div
    class="keen-slider__slide number-slide6"
    style="min-width: 75px; max-width: 75px"
  >
    6
  </div>
</div>
