// ios-like-picker/time/react/src/App.js
import React from "react"
import Wheel from "./Wheel"
import "./styles.css"

export default () => {
  return (
    <div
      style={{
        height: "200px",
        padding: "50px",
        display: "flex",
        justifyContent: "center",
        background: "#000",
      }}
    >
      <div style={{ width: 70 }}>
        <Wheel initIdx={1} length={24} width={23} />
      </div>
      <div style={{ width: 70 }}>
        <Wheel initIdx={35} length={60} width={23} perspective="left" />
      </div>
    </div>
  )
}

// ios-like-picker/date-time/angular/src/app/app.component.ts

   
import { Component } from "@angular/core"
import { format, subDays } from "date-fns"

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  formatDate(idx) {
    return format(subDays(new Date(), idx), "iii d LLL")
  }
<div
  [ngStyle]="{
    height: '200px',
    padding: '50px',
    display: 'flex',
    'justify-content': 'center',
    background: '#000'
  }"
>
  <div :style="{ width: '150px' }">
    <wheel
      [loop]="true"
      [length]="24"
      [width]="140"
      perspective="right"
      [setValue]="formatDate"
    ></wheel>
  </div>
  <div [ngStyle]="{ width: '70px' }">
    <wheel [loop]="true" [length]="24" [width]="23"></wheel>
  </div>
  <div [ngStyle]="{ width: '70px' }">
    <wheel [loop]="true" [length]="60" [width]="23" perspective="left"></wheel>
  </div>
</div>
